### ISSUE TITLE
unable to connect to the docker daemon in jenkins-agent

### ISSUE THREAD

**Issue by Omar-El** [jenkinsci/docker-agent#149]
I'm trying to build a docker image in a jenkins agent, so first of all i spun up the jenkins master container without mounting the docker socket as you can see bellow, i'm able to connect to the docker daemon from the master agent, but when running the pipeline the docker cli located in the jenkins agent cannot reach out to the api, even though i supplied the docker certificate credentials, i think it has to do with tcp://docker:2376? do you have any suggestions ?
![image](https://user-images.githubusercontent.com/37773673/88468372-615e8c00-ceda-11ea-9990-19bfcdf5a2e1.png)

jenkisfile :
```
pipeline {
  agent {
    node {
      label 'jenkins-agent'
    }

  }
  stages {
    stage('Checkout') {
      steps {
        cleanWs()
        checkout scm
      }
    }

    stage('Docker Build') {
      steps {
        script {
          withCredentials([dockerCert(credentialsId: 'ec19d1e1-bea2-4e75-9dac-49c49fbfa303', variable: 'DOCKER_CERT_PATH')]) {
            configFileProvider([configFile(fileId: '54e67686-6227-4d56-9606-cc23bdbad5d4', variable: 'MAVEN_SETTINGS')])
            { sh 'echo $DOCKER_HOST'
            sh ' mvn clean install -B -s $MAVEN_SETTINGS -DskipTests=True'
          }
        }
      }

    }
  }

}

}
options {
  skipDefaultCheckout()
  disableConcurrentBuilds()
}
} 
``` 

docker compose file:
``` 
  - name: Spin up containers
    docker_compose:
        project_name: jenkins-nginx
        definition:
          version: '2'
          services:
            nginx:
              image: jwilder/nginx-proxy
              restart: unless-stopped
              privileged: true
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - /home/ubuntu/certs:/etc/nginx/certs
                - /var/run/docker.sock:/tmp/docker.sock:ro
              depends_on:
                   - jenkins
              networks:
                 - jenkins        
            jenkins:
              restart: unless-stopped
              image: jenkinsci/blueocean
              volumes:
                - jenkins-home:/var/jenkins_home
                - jenkins-docker-certs:/certs/client
              networks:
                 - jenkins
              depends_on:
                   - jenkins-docker    
              environment:
                  VIRTUAL_HOST: jenkins-server.ga
                  VIRTUAL_PORT: 8080
                  DOCKER_HOST: "tcp://docker:2376"
                  DOCKER_CERT_PATH: "/certs/client"
                  DOCKER_TLS_VERIFY: "1"
            jenkins-docker:
              restart: unless-stopped
              privileged: true
              image: docker:dind
              volumes: 
                - /home/ubuntu/jenkins_home:/var/jenkins_home   
                - jenkins-docker-certs:/certs/client
              networks:
                  "jenkins":
                    "aliases":
                       - docker
              environment:
                  DOCKER_TLS_CERTDIR: /certs  
              ports:
                - "2376:2376"
          volumes:
             jenkins-docker-certs:
             jenkins-home:
          networks:
             jenkins:
```
