### ISSUE TITLE
Jenkins Agent error and exit

### ISSUE THREAD

**Issue by Guillaume-Mayer** [jenkinsci/docker-agent#19]
Trying to run a master and a agent with the following docker-compose.yml:

```yaml
version: "2.2"
services:
  master:
    image: jenkins/jenkins:alpine
    ports:
    - 8080:8080
    volumes:
    - ./jenkins_home:/var/jenkins_home
  slave:
    image: jenkins/slave:alpine
    command: ["java", "-jar", "/usr/share/jenkins/slave.jar"]
    init: true
```

But I get this error:

Exception in thread "main" java.io.EOFException: unexpected stream termination
        at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:378)
        at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:323)
        at hudson.remoting.Launcher.main(Launcher.java:742)
        at hudson.remoting.Launcher.runWithStdinStdout(Launcher.java:680)
        at hudson.remoting.Launcher.run(Launcher.java:362)
        at hudson.remoting.Launcher.main(Launcher.java:277)
<===[JENKINS REMOTING CAPACITY]===>rO0ABXNyABpodWRzb24ucmVtb3RpbmcuQ2FwYWJpbGl0eQAAAAAAAAABAgABSgAEbWFza3hwAAAAAAAAAP4=
