### ISSUE TITLE
Root directory not writable: /home/jenkins/.jenkins/cache/jars

### ISSUE THREAD

**Issue by hanrw** [jenkinsci/docker-agent#713]
```
version: '2'
services:
  jenkinsci-slave5:
    image: jenkinsci/jnlp-slave
    environment:
      JENKINS_AGENT_NAME: jenkins-slave
      JENKINS_SECRET: fac1f848bf46d90440979a3e9914f5e412b49b7ebf1fe0adc4bfa2ad2fcd349b
      JENKINS_URL: master
    volumes:
    - /home/jenkins/slave-1-home:/home/jenkins
    - /home/jenkins/m2/repository:/home/.m2/repository
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: alway
```
We are want keep the data to the same place.
But it's got exception when we mount volume on it.
