### ISSUE TITLE
Add an updatecli manifest to track UBI9 docker image version

### ISSUE THREAD

**Issue by lemeurherveCB** [jenkinsci/docker-agent#883]
### What feature do you want to see added?

#866 introduced UBI9 agents, refined in #880 but there is no updatecli manifest to keep `UBI9_TAG` up to date in the Dockerfile and in the docker-bake.hcl files.

I got a first version that I removed in https://github.com/jenkinsci/docker-agent/pull/880/commits/ea742576977655f45756b82bd50d10569397f862

Without any additional spec the last tag returned is `sha256-14f1cd4b565c93b7ae400db1759db485f14a9154d45f25c9558cd2a9e753d2ca.att`(wrong one):
```yaml
sources:
  latestVersion:
    kind: dockerimage
    name: "Get the latest UBI9 Linux version"
    spec:
      image: "registry.access.redhat.com/ubi9/ubi"
```

Using `versionfilter: semver` + `trimsuffix: "-source"` also returns wrong version:
```yaml
sources:
  latestVersion:
    kind: dockerimage
    name: "Get the latest UBI9 Linux version"
    spec:
      image: "registry.access.redhat.com/ubi9/ubi"
      versionfilter:
        kind: semver
    transformers:
      - trimsuffix: "-source"
```
> The line #1, matched by the keyword "ARG" and the matcher "UBI9_TAG", is changed from "ARG UBI9_TAG="9.4-1214.1726694543" to "ARG UBI9_TAG=9.4".

Same with a regexp pattern, wrong version returned.
```yaml
sources:
  latestVersion:
    kind: dockerimage
    name: "Get the latest UBI9 Linux version"
    spec:
      image: "registry.access.redhat.com/ubi9/ubi"
      versionfilter:
        kind: regexp
        pattern: \d+\.\d+-\d+\.\d+
    transformers:
      - trimsuffix: "-source"
```
> The line #1, matched by the keyword "ARG" and the matcher "UBI9_TAG", is changed from "ARG UBI9_TAG="9.4-1214.1726694543" to "ARG UBI9_TAG=9.4-947.1717074712".
